{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gorestic-homelab.fullname" . }}-secrets
  labels:
    {{- include "gorestic-homelab.labels" . | nindent 4 }}
type: Opaque
stringData:
  RESTIC_PASSWORD: {{ .Values.secrets.resticPassword | quote }}
  {{- if .Values.secrets.postgresPassword }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.telegramBotToken }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramBotToken | quote }}
  {{- end }}
  {{- if .Values.secrets.telegramChatId }}
  TELEGRAM_CHAT_ID: {{ .Values.secrets.telegramChatId | quote }}
  {{- end }}
{{- end }}
