{{- if and .Values.sshKey.enabled (not .Values.sshKey.existingSecret) .Values.sshKey.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gorestic-homelab.fullname" . }}-ssh-key
  labels:
    {{- include "gorestic-homelab.labels" . | nindent 4 }}
type: Opaque
stringData:
  id_rsa: {{ .Values.sshKey.privateKey | quote }}
{{- end }}
