apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - configmap.yaml
  - pvc.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/name: gorestic-homelab
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/fgeck/gorestic-homelab
    newTag: latest
