apiVersion: v1
kind: Secret
metadata:
  name: gorestic-secrets
  labels:
    app.kubernetes.io/name: gorestic-homelab
type: Opaque
stringData:
  # Required
  RESTIC_PASSWORD: "changeme"
  # Optional - uncomment if using PostgreSQL backup
  # POSTGRES_PASSWORD: "changeme"
  # Optional - uncomment if using Telegram notifications
  # TELEGRAM_BOT_TOKEN: "123456:ABC-DEF"
  # TELEGRAM_CHAT_ID: "-1001234567890"
